### PR TITLE
Feature/jw 39 questionnaire pictures

### PR DESCRIPTION
**Pull request by bpb2008**
### Description
Added pictures into the questionnaire, based on the design specifications. 

### Related Issue
[JW-39](https://marisolsaumi.atlassian.net/browse/JW-39?atlOrigin=eyJpIjoiMjQ4NmFiNmE3ZDdlNGM1M2EyYmQzYWJmYmRlZDc0M2YiLCJwIjoiaiJ9) : As a User I can answer a multiple choice questionnaire

### Description of Changes
* Added in photos based on designers specifications. 
* Questionnaire starts out with archetype photos/descriptions, where users can read and learn about archetypes. 
* After the first archetype question, photos change based on the question. 

### Checklist
- [x] I have read the CONTRIBUTING.md document.
- [x] My code follows the code style of this project.
- [ ] I have added suitable test coverage for the changes made.
- [x] My changes generate no new warnings or errors.
- [ ] I have updated the documentation or comments where necessary.
- [x] All tests pass locally.

### Testing Instructions
* N/A

### Screenshots (if applicable)
Screenshot 2024-05-18 at 10 23 23 PM

### Gotchas/Learnings
*N/A

### Additional Notes (Optional)
* N/A

### CODE REVIEW

**Review by Mahiambaw — APPROVED** [review]

**Comment by lmose820** [comment]
First time I noticed the speed of the image took awhile to load. The second time opening the deploy preview link it was fast.

**Comment by lmose820** [comment]
questionnaire photos did not respond when minimizing laptop browser. Maybe because responsiveness is moving to the next sprint.

**Comment by bpb2008** [comment]
> 

Hey Lara! I did notice this when I was testing out these changes last night. I'm trying to come up with a solution for this. If it is possible, can we add that and the responsiveness to sprint 3?

**Comment by aasharma01** [comment]
This looks so good! For some reason when I start the quiz, I can't view the archetypes images. With regard to the 3 dots below the archetype card, is it possible to have it so that the archetype the user is currently viewing is filled white, and the unselected ones have a white border? Like this: 
Screen Shot 2024-05-22 at 12 14 20 PM

**Pull request merged**
